language: julia
os:
  - linux
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
env:
  - TEST_TYPE=basic
  # - TEST_TYPE=bench
  - TEST_TYPE=userimage
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - env: TEST_TYPE=bench
    - julia: 0.7
      env: TEST_TYPE=userimage
    - julia: 1.0
      env: TEST_TYPE=userimage
  include:
    - if: branch = master
      julia: 0.6
      os: osx
      env: TEST_TYPE=basic
  exclude:
    - julia: nightly
      env: TEST_TYPE=userimage

notifications:
  email: false
script:
  - ./.travis/test.sh
after_success:
  - |
      julia -e '
        VERSION >= v"0.7.0-DEV.3656" && using Pkg
        VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Memento"))
        Pkg.add("Coverage")
        using Coverage
        Codecov.submit(Codecov.process_folder())
      '
  - |
      julia -e '
        VERSION >= v"0.7.0-DEV.3656" && using Pkg
        VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Memento"))
        Pkg.add("Documenter")
        include(joinpath("docs", "make.jl"))
      '
