language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
env:
  - TEST_TYPE=parallel
  - TEST_TYPE=io
  - TEST_TYPE=bench
  - TEST_TYPE=userimage
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - env: TEST_TYPE=bench
  exclude:
    - julia: nightly
      env: TEST_TYPE=userimage
    - julia: 0.5
      env: TEST_TYPE=userimage
    - julia: 0.5
      env: TEST_TYPE=bench
    - os: osx
      env: TEST_TYPE=bench

notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Memento")'
  - ./.travis/test.sh
after_success:
  - julia -e 'cd(Pkg.dir("Memento")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("Memento")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
