language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("Memento")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
