site_name:        Memento.jl
repo_url:         https://github.com/invenia/Memento.jl
site_description: A flexible logging library for julia
site_author:      rory.finnegan@invenia.ca

theme: readthedocs

extra_css:
  - assets/Documenter.css
  - assets/invenia.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
